-- Initial schema for the student ride-sharing application.
-- RLS policies are intentionally handled in a follow-up migration once the
-- application queries and visibility rules can be tested end-to-end.

create extension if not exists pgcrypto;

create type public.profile_gender as enum (
  'woman',
  'man',
  'non_binary',
  'prefer_not_to_say'
);

create type public.fuel_type as enum (
  'petrol',
  'diesel',
  'hybrid',
  'electric',
  'lpg',
  'other'
);

create type public.ride_gender_preference as enum ('any', 'same_as_driver');
create type public.ride_status as enum ('draft', 'published', 'full', 'completed', 'cancelled');
create type public.ride_source as enum ('native', 'imported');
create type public.booking_status as enum ('requested', 'accepted', 'declined', 'cancelled');

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text not null check (char_length(trim(full_name)) between 2 and 100),
  photo_url text not null,
  university text not null check (char_length(trim(university)) between 2 and 160),
  phone text,
  instagram text,
  facebook text,
  bio text check (bio is null or char_length(bio) <= 500),
  gender public.profile_gender,
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.cities (
  id bigint generated by default as identity primary key,
  name_mk text not null unique,
  name_en text not null unique,
  aliases text[] not null default '{}',
  lat double precision not null check (lat between -90 and 90),
  lng double precision not null check (lng between -180 and 180),
  created_at timestamptz not null default now()
);

create table public.pickup_points (
  id bigint generated by default as identity primary key,
  city_id bigint not null references public.cities (id) on delete cascade,
  name_mk text not null,
  name_en text not null,
  aliases text[] not null default '{}',
  lat double precision not null check (lat between -90 and 90),
  lng double precision not null check (lng between -180 and 180),
  created_at timestamptz not null default now(),
  unique (city_id, name_mk),
  unique (city_id, name_en),
  unique (id, city_id)
);

create table public.car_models (
  id bigint generated by default as identity primary key,
  make text not null,
  model text not null,
  fuel_type public.fuel_type not null,
  consumption_l_100km numeric(4, 1) not null check (consumption_l_100km > 0),
  created_at timestamptz not null default now(),
  unique (make, model, fuel_type)
);

create table public.cars (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles (id) on delete cascade,
  car_model_id bigint references public.car_models (id) on delete set null,
  make text not null,
  model text not null,
  fuel_type public.fuel_type not null,
  consumption_l_100km numeric(4, 1) not null check (consumption_l_100km > 0),
  color text,
  plate_last3 text check (plate_last3 is null or plate_last3 ~ '^[[:alnum:]]{3}$'),
  seats_total smallint not null check (seats_total between 1 and 8),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.imports (
  id uuid primary key default gen_random_uuid(),
  raw_text text not null check (char_length(trim(raw_text)) > 0),
  source_hint text,
  parsed_json jsonb not null default '{}'::jsonb check (jsonb_typeof(parsed_json) = 'object'),
  confidence numeric(4, 3) check (confidence between 0 and 1),
  spam_flags text[] not null default '{}',
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.rides (
  id uuid primary key default gen_random_uuid(),
  driver_id uuid references public.profiles (id) on delete restrict,
  car_id uuid references public.cars (id) on delete set null,
  origin_city_id bigint not null references public.cities (id),
  origin_pickup_id bigint,
  dest_city_id bigint not null references public.cities (id),
  dest_pickup_id bigint,
  departure_at timestamptz not null,
  seats_total smallint not null check (seats_total between 1 and 8),
  seats_available smallint not null check (seats_available between 0 and seats_total),
  price_per_seat_mkd integer check (price_per_seat_mkd is null or price_per_seat_mkd >= 0),
  notes text check (notes is null or char_length(notes) <= 2000),
  details jsonb not null default '{}'::jsonb check (jsonb_typeof(details) = 'object'),
  tags text[] not null default '{}',
  gender_preference public.ride_gender_preference not null default 'any',
  status public.ride_status not null default 'draft',
  source public.ride_source not null default 'native',
  import_id uuid references public.imports (id) on delete restrict,
  claimed_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (origin_pickup_id, origin_city_id)
    references public.pickup_points (id, city_id),
  foreign key (dest_pickup_id, dest_city_id)
    references public.pickup_points (id, city_id),
  check (origin_city_id <> dest_city_id),
  check (
    (source = 'native' and driver_id is not null)
    or (source = 'imported' and import_id is not null)
  )
);

create table public.bookings (
  id uuid primary key default gen_random_uuid(),
  ride_id uuid not null references public.rides (id) on delete cascade,
  passenger_id uuid not null references public.profiles (id) on delete cascade,
  seats smallint not null default 1 check (seats between 1 and 8),
  message text check (message is null or char_length(message) <= 1000),
  status public.booking_status not null default 'requested',
  decided_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (status in ('accepted', 'declined') and decided_at is not null)
    or (status in ('requested', 'cancelled'))
  )
);

create table public.ride_comments (
  id uuid primary key default gen_random_uuid(),
  ride_id uuid not null references public.rides (id) on delete cascade,
  author_id uuid not null references public.profiles (id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.messages (
  id uuid primary key default gen_random_uuid(),
  ride_id uuid not null references public.rides (id) on delete cascade,
  sender_id uuid not null references public.profiles (id) on delete cascade,
  recipient_id uuid not null references public.profiles (id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 4000),
  created_at timestamptz not null default now(),
  read_at timestamptz,
  check (sender_id <> recipient_id)
);

create table public.ratings (
  id uuid primary key default gen_random_uuid(),
  ride_id uuid not null references public.rides (id) on delete cascade,
  rater_id uuid not null references public.profiles (id) on delete cascade,
  ratee_id uuid not null references public.profiles (id) on delete cascade,
  score smallint not null check (score between 1 and 5),
  note text check (note is null or char_length(note) <= 1000),
  created_at timestamptz not null default now(),
  check (rater_id <> ratee_id),
  unique (ride_id, rater_id, ratee_id)
);

create table public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references public.profiles (id) on delete cascade,
  target_user_id uuid references public.profiles (id) on delete set null,
  ride_id uuid references public.rides (id) on delete set null,
  reason text not null check (char_length(trim(reason)) between 1 and 100),
  body text check (body is null or char_length(body) <= 2000),
  created_at timestamptz not null default now(),
  check (target_user_id is not null or ride_id is not null),
  check (target_user_id is null or reporter_id <> target_user_id)
);

create table public.trip_shares (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid not null references public.bookings (id) on delete cascade,
  token text not null unique default encode(gen_random_bytes(24), 'hex'),
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  check (expires_at > created_at)
);

create index pickup_points_city_id_idx on public.pickup_points (city_id);
create index cars_owner_id_idx on public.cars (owner_id);
create index rides_feed_idx on public.rides (status, departure_at);
create index rides_route_idx on public.rides (origin_city_id, dest_city_id, departure_at);
create index rides_driver_id_idx on public.rides (driver_id, departure_at desc);
create index bookings_ride_status_idx on public.bookings (ride_id, status);
create index bookings_passenger_id_idx on public.bookings (passenger_id, created_at desc);
create unique index bookings_one_active_per_passenger_ride_idx
  on public.bookings (ride_id, passenger_id)
  where status in ('requested', 'accepted');
create index ride_comments_ride_id_idx on public.ride_comments (ride_id, created_at);
create index messages_conversation_idx on public.messages (ride_id, created_at);
create index ratings_ratee_id_idx on public.ratings (ratee_id, created_at desc);
create index reports_target_user_id_idx on public.reports (target_user_id)
  where target_user_id is not null;

create function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger cars_set_updated_at
before update on public.cars
for each row execute function public.set_updated_at();

create trigger rides_set_updated_at
before update on public.rides
for each row execute function public.set_updated_at();

create trigger bookings_set_updated_at
before update on public.bookings
for each row execute function public.set_updated_at();

create trigger ride_comments_set_updated_at
before update on public.ride_comments
for each row execute function public.set_updated_at();

create function public.recalculate_ride_seats(target_ride_id uuid)
returns void
language plpgsql
set search_path = ''
as $$
declare
  capacity smallint;
  accepted_seats integer;
  remaining_seats integer;
begin
  select seats_total
  into capacity
  from public.rides
  where id = target_ride_id
  for update;

  if capacity is null then
    return;
  end if;

  select coalesce(sum(seats), 0)
  into accepted_seats
  from public.bookings
  where ride_id = target_ride_id
    and status = 'accepted';

  remaining_seats := capacity - accepted_seats;

  if remaining_seats < 0 then
    raise exception 'Ride % does not have enough available seats', target_ride_id
      using errcode = '23514';
  end if;

  update public.rides
  set
    seats_available = remaining_seats,
    status = case
      when remaining_seats = 0 and status = 'published' then 'full'::public.ride_status
      when remaining_seats > 0 and status = 'full' then 'published'::public.ride_status
      else status
    end
  where id = target_ride_id;
end;
$$;

create function public.sync_ride_seats()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  perform public.recalculate_ride_seats(
    case when tg_op = 'DELETE' then old.ride_id else new.ride_id end
  );

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;

create function public.guard_booking_identity()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.ride_id <> old.ride_id or new.passenger_id <> old.passenger_id then
    raise exception 'A booking ride and passenger cannot be changed'
      using errcode = '23514';
  end if;

  return new;
end;
$$;

create trigger bookings_guard_identity
before update on public.bookings
for each row execute function public.guard_booking_identity();

create trigger bookings_sync_ride_seats
after insert or update or delete on public.bookings
for each row execute function public.sync_ride_seats();

create function public.guard_ride_capacity_change()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  accepted_seats integer;
begin
  if new.seats_total = old.seats_total then
    return new;
  end if;

  select coalesce(sum(seats), 0)
  into accepted_seats
  from public.bookings
  where ride_id = new.id
    and status = 'accepted';

  if new.seats_total < accepted_seats then
    raise exception 'Ride capacity cannot be lower than accepted seats (%)', accepted_seats
      using errcode = '23514';
  end if;

  new.seats_available := new.seats_total - accepted_seats;
  return new;
end;
$$;

create trigger rides_guard_capacity_change
before update of seats_total on public.rides
for each row execute function public.guard_ride_capacity_change();

comment on column public.rides.details is
  'Optional structured add-ons (for example rules, luggage, or preferences). Stable/filterable concepts must become columns.';
